### ISSUE TITLE
Training on Tanks and Temples Dataset

### ISSUE THREAD

**Issue by doubleZ0108** [princeton-vl/CER-MVS#3]
Hi, thanks for your great work!
I just downloaded the provided Tanks and Temples Training Dataset, but there are only `cams`, `images`, and `pair.txt` in each scan.
So I just wonder how to train on TNT Dataset without `depth GT`?
Did I miss something?

**Comment by mazeyu** [comment]
No, we don't train on Tanks and Temples (expect hyper parameter tuning), as is the practice of previous works.
