### ISSUE TITLE
question about alt_cuda_corr

### ISSUE THREAD

**Issue by XiaoyuShi97** [princeton-vl/CER-MVS#4]
https://github.com/princeton-vl/CER-MVS/blob/6e41bf673472b8e341f6a0e95c8d0ff9b3bf07f5/core/corr.py#L12

Hi! I find that this alt_cuda_corr is the same as that of RAFT. But this function is new. I am not familiar with cuda. Could you explain why you need to define this new function? Thx!

**Comment by mazeyu** [comment]
This new function is an extension of AlternateCorrBlock in RAFT, which implements both forward and backward pass in CUDA. They are written by Zach, the author of RAFT.
