### ISSUE TITLE
Problem in DTU Data Loader

### ISSUE THREAD

**Issue by tom-bu** [princeton-vl/CER-MVS#5]
I'm trying to train the model on DTU. But I'm getting a key error of 62 in line 115 of dtu.py. This is because in some scans there are 64 cameras, but in the ground truth pairs.txt, there is only pair information for the first 49 cameras. How do I fix this? Should I limit the number of cameras to the first 49?

**Comment by mazeyu** [comment]
[delete] (I might used pairs_provided=False in training but mistakenly put it True in the code here. You can try it with False. Sorry for inconvenience)
(it is not related to pairs_provided)
I think I somehow just ignored the rest of the 15 images but forgot to put it into the code.
