### ISSUE TITLE
T&T scale

### ISSUE THREAD

**Issue by maorp** [princeton-vl/CER-MVS#7]
Hi thanks for the great work! I have a question about this scale param in TNT dataset, its used to scale the extrinsics position. i see scale_info[0] is read from cams.txt for every frame (min depth as far as i understand). how should i handle this for my own dataset? i have calibrated cameras. DTU dataset does not do it...

scale = 400 / scale_info[0]

**Comment by mazeyu** [comment]
If you have a sparse reconstruction when you calibrate the camera then you can do it similarly by setting scale to 400 / min distance.
